list_flat:
    pattern:  /list_flat
    defaults: { _controller: AdminBundle:Flat:index }

new_flat:
    pattern:  /new_flat
    defaults: { _controller: AdminBundle:Flat:new }

create_flat:
    pattern:  /create_flat
    defaults: { _controller: AdminBundle:Flat:create }

show_flat:
    pattern:  /show_flat/{id}
    defaults: { _controller: AdminBundle:Flat:show }
